<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call('UsersTableSeeder');
		
		$products = [
			["product_name" => "Digital Smart sport watch Women watches digital led electronic wristwatch Bluetooth fitness wristwatch Men kids hours hodinky|Women's Watches|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/3aaea943580384f771a28d6a07f8ad15-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=digital-smart-sport-watch-women-watches-digital-led-electronic-wristwatch-bluetooth-fitness-wristwatch-men-kids-hours-hodinkywomens-watches-aliexpress"],
			["product_name" => "LED Digital Alarm Clock Watch Table Electronic Desktop Clocks USB Wake Up FM Radio Time Projector Snooze Function 2 Alarm|Alarm Clocks|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/c2f4ee32375ac612554c13200343c058-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=led-digital-alarm-clock-watch-table-electronic-desktop-clocks-usb-wake-up-fm-radio-time-projector-snooze-function-2-alarmalarm-clocks-aliexpress"],
			["product_name" => "GAOMON PD1161 IPS HD Graphics Drawing Display Digital Tablet Monitor With 8 Shortcut Keys & 8192 Levels Battery Free Pen|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/817245699395349790e94c613f4f9c30-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=gaomon-pd1161-ips-hd-graphics-drawing-display-digital-tablet-monitor-with-8-shortcut-keys-8192-levels-battery-free-pendigital-tablets-aliexpress"],
			["product_name" => "SHAHE 4*90 degree Digital Electronic Level and Angle Gauge Inclinometer with Backlight and Magnetic Base Protractor Digital|Protractors|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/d716667555bc82e9f657f560b04776cc-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=shahe-490-degree-digital-electronic-level-and-angle-gauge-inclinometer-with-backlight-and-magnetic-base-protractor-digitalprotractors-aliexpress"],
			["product_name" => "FM Radio LED Digital Smart Alarm Clock Watch Table Electronic Desktop Clocks USB Wake Up Clock with 180° Time Projector Snooze|Alarm Clocks|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/6571b17aa0ef2a8bc28bb08bf43aa051-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=fm-radio-led-digital-smart-alarm-clock-watch-table-electronic-desktop-clocks-usb-wake-up-clock-with-180-time-projector-snoozealarm-clocks-aliexpress"],
			["product_name" => "LIGE 2022 New Steel Band Digital Watch Men Sport Watches Electronic LED Male Wrist Watch For Men Clock Waterproof Bluetooth Hour|Digital Watches|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/dbd8f704bc93ada3685b58b9368abb52-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=lige-2022-new-steel-band-digital-watch-men-sport-watches-electronic-led-male-wrist-watch-for-men-clock-waterproof-bluetooth-hourdigital-watches-aliexpress"],
			["product_name" => "NORTH EDGE Men Digital Watch Men's Sports Watches Dual Time Pedometer Alarm Clock Waterproof 50M Digital Watch Military Clock|Digital Watches|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/aebfcea18329724a3a8db5cf9c92c6ce-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=north-edge-men-digital-watch-mens-sports-watches-dual-time-pedometer-alarm-clock-waterproof-50m-digital-watch-military-clockdigital-watches-aliexpress"],
			["product_name" => "NORTH EDGE Men's sport Digital watch Hours Running Swimming Military Army watches Altimeter Barometer Compass waterproof 50m|Digital Watches|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/42b778b696bd65d4260faf4f8cb6be79-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=north-edge-mens-sport-digital-watch-hours-running-swimming-military-army-watches-altimeter-barometer-compass-waterproof-50mdigital-watches-aliexpress"],
			["product_name" => "10.1 Inch HD Digital Photo Frame 1024x600 HD Ultra Thin LED Electronic Photo Album LCD Photo Frame|Digital Photo Frames|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/c5c5a1a1cb3e666bdedcc64d127bc2da-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=10-1-inch-hd-digital-photo-frame-1024x600-hd-ultra-thin-led-electronic-photo-album-lcd-photo-framedigital-photo-frames-aliexpress"],
			["product_name" => "XP Pen Artist 12 11.6‘’ Graphics Tablet Drawing Graphic Monitor Animation Digital 1920 X 1080HD IPS  Shortcut Keys and Touch Pad|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/9a3148b402619cff55e8485cbba3a52d-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=xp-pen-artist-12-11-6-graphics-tablet-drawing-graphic-monitor-animation-digital-1920-x-1080hd-ips-shortcut-keys-and-touch-paddigital-tablets-aliexpress"],
			["product_name" => "Digital Watch Women Sport Men Watches Electronic LED Ladies Wrist Watch For Android IOS Fitness Clock Female Male Wristwatch+box|Women's Watches|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/c93ad10cf891a1a3b060bef3854833ae-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=digital-watch-women-sport-men-watches-electronic-led-ladies-wrist-watch-for-android-ios-fitness-clock-female-male-wristwatchboxwomens-watches-aliexpress"],
			["product_name" => "XP Pen Artist 12 Pro 11.6 Inches Graphics Tablet Drawing Tablet Monitor Display Animation Digital Art with Tilt 8192 Pressure|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/ecbc6c5e9c5a38eccd12d6b1b1d4897e-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=xp-pen-artist-12-pro-11-6-inches-graphics-tablet-drawing-tablet-monitor-display-animation-digital-art-with-tilt-8192-pressuredigital-tablets-aliexpress"],
			["product_name" => "XP Pen Artist15.6 Pro Drawing Tablet Graphic Monitor Digital Animation Drawing Board with 60 degrees of tilt function Art|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/643c0d15870d7d6f33e079e1dde64626-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=xp-pen-artist15-6-pro-drawing-tablet-graphic-monitor-digital-animation-drawing-board-with-60-degrees-of-tilt-function-artdigital-tablets-aliexpress"],
			["product_name" => "Electronic Protractor Inclinometer Bevel Box Angle finder Digital Inclinometer With Backlight Angle Measurement Angle Gauge|Protractors|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/6316ed1dbde4a8b712716d32b09a983f-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=electronic-protractor-inclinometer-bevel-box-angle-finder-digital-inclinometer-with-backlight-angle-measurement-angle-gaugeprotractors-aliexpress"],
			["product_name" => "GAOMON M10K PRO 10 x 6.25 Inches Art Digital Graphic Tablet for Drawing Supports Tilt & Radial Function with 10 Shortcut Keys|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/b7aa2e5acc4fed5ed65b2792892fff88-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=gaomon-m10k-pro-10-x-6-25-inches-art-digital-graphic-tablet-for-drawing-supports-tilt-radial-function-with-10-shortcut-keysdigital-tablets-aliexpress"],
			["product_name" => "Alarm Clock LED Wooden Watch Table Voice Control Digital Wood Despertador USB/AAA Powered Electronic Desktop Clocks|Alarm Clocks|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/ea03ecb8b174e450ad97a1d0bec48732-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=alarm-clock-led-wooden-watch-table-voice-control-digital-wood-despertador-usbaaa-powered-electronic-desktop-clocksalarm-clocks-aliexpress"],
			["product_name" => "XP Pen Deco 01 V2 10 inch Drawing Tablet Graphics Digital Tablet Tilt Android Windows MAC 8 Shortcut Keys (8192 Levels Pressure)|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2018/10/1540284952loading-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=xp-pen-deco-01-v2-10-inch-drawing-tablet-graphics-digital-tablet-tilt-android-windows-mac-8-shortcut-keys-8192-levels-pressuredigital-tablets-aliexpress"],
			["product_name" => "HUION HS610 Graphic Tablets Digital Pen Tablet Phone Drawing Tablet with Tilt OTG Battery Free Stylus for Android Windows macOS|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2018/10/1540284952loading-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=huion-hs610-graphic-tablets-digital-pen-tablet-phone-drawing-tablet-with-tilt-otg-battery-free-stylus-for-android-windows-macosdigital-tablets-aliexpress"],
			["product_name" => "10.1inch Magic Screen Video Frame With 8GB Internal Memory Digital Picture Frame USB SD For Video Play in Loop|Digital Photo Frames|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2018/10/1540284952loading-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=10-1inch-magic-screen-video-frame-with-8gb-internal-memory-digital-picture-frame-usb-sd-for-video-play-in-loopdigital-photo-frames-aliexpress"],
			["product_name" => "SKMEI Fashion Sport Watch Women Top brands Luxury 3Bar Waterproof Ladies Watches Small Dial Digital Watch Relogio Feminino 1252|Women's Watches|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2018/10/1540284952loading-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=skmei-fashion-sport-watch-women-top-brands-luxury-3bar-waterproof-ladies-watches-small-dial-digital-watch-relogio-feminino-1252womens-watches-aliexpress"],
			["product_name" => "HUION HS611 Graphic Digital Drawing Tablet 266PPS Graphics Pen Tablet Multimedia Keys Three Colors For PC Android|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/5a6c865345a3fbef7b696f06a6508a41-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=huion-hs611-graphic-digital-drawing-tablet-266pps-graphics-pen-tablet-multimedia-keys-three-colors-for-pc-androiddigital-tablets-aliexpress"],
			["product_name" => "HUION Q620M Graphics Tablet Wireless USB Drawing Pen Tablet 8192 Levels Pressure Digital Stylus with Dial 8 Keys Support Android|Digital Tablets|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/7578fd00abc1310bf55d5ee877ac20f0-300x300.jpg", "kategori" => 22, "link" => "https://alibabacloudtools.xyz/?product=huion-q620m-graphics-tablet-wireless-usb-drawing-pen-tablet-8192-levels-pressure-digital-stylus-with-dial-8-keys-support-androiddigital-tablets-aliexpress"],
			["product_name" => "New Silicone Digital Watch Men Sport Women Watches Electronic LED Ladies Male Wrist Watch For Men Women Clock Female Wristwatch|Digital Watches|   - AliExpress", "image" => "https://alibabacloudtools.xyz/qfy-content/uploads/2022/02/161dc08c9ac01151477a6359889b4575-300x300.jpg", "kategori" => 5, "link" => "https://alibabacloudtools.xyz/?product=new-silicone-digital-watch-men-sport-women-watches-electronic-led-ladies-male-wrist-watch-for-men-women-clock-female-wristwatchdigital-watches-aliexpress"]
		];
		
		for ($x = 0; $x < count($products); $x++) {
			DB::table('products')->insert([
				'product_name' => $products[$x]["product_name"],
				'product_image' => $products[$x]["image"],
				'product_link' => $products[$x]["link"],
				'kategori' => $products[$x]["kategori"],
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now()
			]);
		}
    }
}
